version: '3.9'

services:
  bot:
    env_file:
      - ./bot/tools/.env
    build:
      context: ./bot
    volumes:
      - tools:/logs
      - tools:/bot/tools  # Shared tools directory
    restart: always

  api:
    env_file:
      - ./bot/tools/.env
    build:
      context: .
    volumes:
      - tools:/logs
      - tools:/bot/tools
    ports:
      - "8000:8000"
    restart: always

  db:
    image: "postgres:16"
    hostname: 'pgdb'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=tb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    container_name: bot_db
    restart: always

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    hostname: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always

  receiver:
    build:
      context: ./bot/rabbit
    command: ["python3", "receiver.py"]
    depends_on:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - tools:/logs
      - tools:/bot/tools  # Shared tools directory
    labels:
      - "preserve=true"  # Label to prevent pruning
    restart: always

volumes:
  coins_trade:
  tools:  # This ensures tools is a named volume