version: '3.9'

services:
  bot:
    env_file:
      - ./tools/.env
    build:
      context: .
    volumes:
      - tools:/logs
    restart: unless-stopped

  db:
    image: "postgres:16"
    hostname: 'pgdb'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=tb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    container_name: bot_db
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    restart: unless-stopped

volumes:
  coins_trade:
  pgdbdata:
  tools:   # Add this volume definition
  restarting:   # Define the 'restarting' volume if needed