name: Deploy Trading Bot

on:
  push:
    branches:
      - main  # Change this if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Debug Secrets
      - name: Print Docker secrets
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"
          echo "DOCKER_PASSWORD length=${#DOCKER_PASSWORD}"
        shell: bash

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bot-api:latest -f ./bot/Dockerfile ./bot
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bot-receiver:latest -f ./bot/rabbit/Dockerfile ./bot/rabbit
          docker push ${{ secrets.DOCKER_USERNAME }}/bot-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/bot-receiver:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/Trade-Bot/Model  # Change to your project directory
            git pull origin main
            docker-compose down
            docker-compose pull
            docker-compose build
            docker-compose up -d --remove-orphans
            docker system prune -af  # Cleanup old images
